### ISSUE TITLE
Logo

### ISSUE THREAD

**Issue by saltfish666** [saltfish666/nclone#1]
Hi @zuurw 
  this project 's aim is let people clone any reposities' dir-tree and file-tree with any depth frome github to local. 
It can help people reuse their project's templete.

En, no idea about what logo should like, you free imagination

**Comment by zuurw** [comment]
Hi @saltfish666,

I will try to get inspiried in something :)

Thanks.

Cheers!

**Comment by zuurw** [comment]
Hi @saltfish666, here is my design for your project, so for the concept I create a files folder and I cloned to other one that I put upside down, then I mixed the two images.

The result is a simple logo with a modern look, I create two variations of the logo.

If you want other colors I can change it for you.

Cheers!

![nclone proposal](https://user-images.githubusercontent.com/40801473/42737392-632bb750-886a-11e8-8112-d5c23e61616b.png)

**Comment by saltfish666** [comment]
Hi, @zuurw 
It is nice to this app!
Full of Texture. (sorry for poor English)
En, and how about making a horizontal icon to suit README? 
Just like adding the previous icon left and set a github icon right, and use a pipe to contact each.
you decide it.

Color is nice, and you can make a pull request, or merge it yourself.
By the way, do you use the Angular specification to fix Git message? If not you can make a pull request, and let me merge it.

**Comment by saltfish666** [comment]
Thank for you inspire, this tool increases many users this week.

**Comment by zuurw** [comment]
Hi, @saltfish666 
Im happy that yo like it, I will send you all the files and create one for the README.md file too.
Witch logo fo you like more de 1# or 2#? 
Do you prefer the dark gray or the light gray color?

For me I like the 2# with the dark gray, because In little size it looks better.

But you decide what you want :)

Best Regards!

**Comment by saltfish666** [comment]
I like dark green too.
@zuurw

**Comment by zuurw** [comment]
Hi @saltfish666, here are some colors combinations, see if you really like one.

Regards!

![colors proposal](https://user-images.githubusercontent.com/40801473/42810777-a38833ae-89b0-11e8-83d7-3cfe22d44d9d.png)

**Comment by saltfish666** [comment]
hi @zuurw  delicious！
if (4,2) mean to Row 4 column 2 

I would like 
(2, 1)
(4, 2)
(5, 2)
(6, 2)
(8, 2)
(9, 2)
(10 ,1)
(12, 1)
please put them together

**Comment by zuurw** [comment]
Ok @saltfish666, I will send all this in the PR, but witch one will be  the main logo to put in the README.md file?

Beste Regards!

**Comment by saltfish666** [comment]
@zuurw  (6,2)

**Comment by zuurw** [comment]
Ok I will prepair the files to create the PR.

**Comment by zuurw** [comment]
Hi @saltfish666 
I create the PR of the logo that you want and I will send also the other colors with diferent colors variaitions, the logo looks good on the README.md file :)

Best Regards!

**Comment by zuurw** [comment]
Hi @saltfish666, thank you for merged the PR, I will send the other colors variations too.

Do you have other project to work?

Best Regards!

**Comment by saltfish666** [comment]
Hi @zuurw 
not yet.
How long would you continue design logo for the open project? 
I have some idea to programming by not time right now.
I will inform you in the future if you don't mind.

Best Regards!
